apiVersion: apps/v1
kind: Deployment
metadata:
  Name: spring-jenkins
spec:
  selector:
    matchLabels:
      app: spring-jenkins
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-jenkins
    spec:
      containers:
        - name: spring-jenkins
          image: lowdisk17/springjenkins
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888


---

apiVersion: v1
kind: Service
metadata:
  name: springjenkins
spec:
  selector:
    app: spring-jenkins
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  type: NodePort
